[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "joblib>=1.4.2",
    "lightgbm>=4.6.0",
    "numpy>=2.2.4",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
]
