service: aws-python-flask-api

frameworkVersion: "4"

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    layer: true
    dockerizePip: true
    zip: true
    slim: true # Removes unnecessary files from dependencies
    noDeploy:
      - pandas
      - numpy
      - scikit-learn # Exclude these if using AWS Lambda Layer

provider:
  name: aws
  runtime: python3.12

functions:
  api:
    layers:
      - Ref: PythonRequirementsLambdaLayer
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
